server:
  port: 8081

# 配置数据源，使用Druid数据源
spring:
  datasource:
    name: seckill
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1741248769
    type: com.alibaba.druid.pool.DruidDataSource


# 配置mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
